[versions]
ftc = "10.3.0"

[libraries]
ftc-robot-core = { group = "org.firstinspires.ftc", name = "RobotCore", version.ref = "ftc" }
ftc-hardware = { group = "org.firstinspires.ftc", name = "Hardware", version.ref = "ftc" }
panels = { group = "com.bylazar", name = "fullpanels", version = "0.0.23" }

annotations = { group = "org.jetbrains", name = "annotations", version = "23.0.0" }

[bundles]
ftc = ["ftc-robot-core", "ftc-hardware"]

[plugins]
android-library = { id = "com.android.library", version = "8.7.3" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }